### ISSUE TITLE
Unable to locate Mix file: /js/manifest.js

### ISSUE THREAD

**Issue by kgp43** [zacksmash/fortify-uikit#3] opened 2020-10-13 07:03 UTC
Hi,

First I would like to thank you for making this package.
Got a small problem/error though, after following the installation guide:

`Unable to locate Mix file: /js/manifest.js. (View: ...\resources\views\layouts\app.blade.php)`

I followed the installation guide (fresh install):
- (installed laravel for new project) composer create-project --prefer-dist laravel/laravel test
- composer require zacksmash/fortify-ui
- php artisan fortify-ui:install
- php artisan migrate
- composer require zacksmash/fortify-uikit
- php artisan fortify-ui:uikit
- npm install && npm run dev

**Comment by kgp43** [comment] 2020-10-13 07:49
I did a second npm run dev and now it works.
Not sure what caused this.

**Comment by zacksmash** [comment] 2020-10-13 13:52
@kgp43 

Glad you like it!

So, what the issue is, is that the `package.json` is pretty bare, and when Mix attempts to run, it recognizes that it needs extra dependencies. So, it installs them, but instead of installing all dependencies, it only installs the one that it recognized first. So, you may have to run `nom run dev` a couple times, and then run `npm run watch`. I may change this in the future, so that the `package.json` file just has everything, but I like the idea of getting the latest version each time. But it will do that anyway? I dunno. Sorry you had issues though, glad you got it working.

**Comment by zacksmash** [comment] 2020-10-13 21:04
@kgp43 It looks like Laravel Mix is about to be bumped to v6 and I will update this when that happens.

**Comment by kgp43** [comment] 2020-10-14 05:34
@zacksmash thanks for the update.
Running npm a few times is no problem at all though :)

**Comment by zacksmash** [comment] 2021-01-11 22:08
@kgp43 Looks like mix just got updated so this will be fixed soon.

As far as teams, I know that would be awesome, but I'm trying to keep this to only the features that Fortify provides. Maybe we can lobby to get Señor Otwell to add it to Fortify, natively!

**Closed** 2021-01-14 15:06 UTC
Labels: enhancement
